### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/css-hotel-maket#1]
По бэстпрактис необходимо доставать свойства объектов с помощью деструктурицазии, так код выглядит гораздо чище и отпадет надобность комментариев с принимаемыми параметрами.Также рекомендуется добавлять классы всем элементам, даже если стилей у них нет. Т.к. классы добавляют семантичности.
![image](https://user-images.githubusercontent.com/10168007/89879310-f48f0580-dbec-11ea-82ac-e05b2034998c.png)

**Comment by mglkn** [comment]
#https://github.com/mglkn/css-hotel-maket/commit/2aa412265642b94e005167ff2930ba93bd68b78b#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by mglkn** [comment]
Я не знал что pug умеет destructuring. В документации этот момент от меня ускользнул
https://github.com/mglkn/css-hotel-maket/commit/2aa412265642b94e005167ff2930ba93bd68b78b#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by mglkn** [comment]
Добавил классы.
https://github.com/mglkn/css-hotel-maket/commit/99f384e03f5c8bd16acbf5f237b9938a20e841ab#diff-25d902c24283ab8cfbac54dfa101ad31
