### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#10]
Название класса должно совпадать с названием блока, но с большой буквы, т.к. все классы именуются с большой буквы.
А нициализироваться классы должны отдельно, в index.js.

Все константы вынесенные за пределы класса, которые именно константы и не предполагается, что они будут когда то меняться - должны именоваться в аперкейсе через нижние подчеркивания. 

Методы, которые вынесены за пределы класса(т.е. функции), по определению не могут быть приватными, поэтому префикс '_' там не нужен.

**Comment by mglkn** [comment]
Спасибо за issue

https://github.com/mglkn/css-hotel-maket/commit/277138020cf7c59584f25d8b612741ea84cde39a
https://github.com/mglkn/css-hotel-maket/commit/1be622105f996f9a300afb8cee7a56a49bca50f7
https://github.com/mglkn/css-hotel-maket/commit/248c89616a7b9cc81186d411dd7c78cdfd25c348
https://github.com/mglkn/css-hotel-maket/commit/fe4b8c5b3e00a9fee7ba2789cdd4b6e91301160e
https://github.com/mglkn/css-hotel-maket/commit/e784b31ce7269e92912897561e5e0a52e746e3f6
https://github.com/mglkn/css-hotel-maket/commit/d0582f2d04599397b84faa33423a6534aa32bc70
https://github.com/mglkn/css-hotel-maket/commit/831daad558e05e72fe727b99757adb9f5b12505b
https://github.com/mglkn/css-hotel-maket/commit/8c3f493d74ffcd9d2ca33215ee32122a52faf7c9

**Comment by Feinminen** [comment]
В таких случаях можно искать элемент не в документе, а внутри рут контейнера. Это и логичнее и так точно не будет никаких непредвиденных ошибок и кода меньше. Можно сделать вместо поля сс classID поле с rootEl
![image](https://user-images.githubusercontent.com/44312820/95284102-8763bd80-0887-11eb-8fd7-0eae0c36dff0.png)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95284242-f04b3580-0887-11eb-9f5c-4bfb3478e511.png)
Не везде поправил константы.

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95284344-33a5a400-0888-11eb-81e5-0aff198fca0a.png)
Также ещё остались скрипты блоков, реализованные не классами. (всё что касается ui-kit-a)
В index.js - е должны быть только импорты / инициализация.

**Comment by mglkn** [comment]
Я 

> 
> 
> В таких случаях можно искать элемент не в документе, а внутри рут контейнера. Это и логичнее и так точно не будет никаких непредвиденных ошибок и кода меньше. Можно сделать вместо поля сс classID поле с rootEl
> ![image](https://user-images.githubusercontent.com/44312820/95284102-8763bd80-0887-11eb-8fd7-0eae0c36dff0.png)

Поправил во всех скриптах.




> 
> 
> ![image](https://user-images.githubusercontent.com/44312820/95284242-f04b3580-0887-11eb-9f5c-4bfb3478e511.png)
> Не везде поправил константы.

Исправил.

> 
> 
> ![image](https://user-images.githubusercontent.com/44312820/95284344-33a5a400-0888-11eb-81e5-0aff198fca0a.png)
> Также ещё остались скрипты блоков, реализованные не классами. (всё что касается ui-kit-a, но есть и в других местах, например в pie-chart-е)
> В index.js - е должны быть только импорты / инициализация.

Я сначала подумал, что именно классы надо выделить в отдельный файл. Теперь понял что для единообразия всю логику выносим из index.js.

Исправил.
