### ISSUE TITLE
Footers

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#11]
У тебя сейчас в проекте 3 футера -  footer-bottom, footer-middle и footer. И именованы они не по БЭМ - они должны описывать смысл того что в них лежит. А у тебя сейчас они описывают расположение - какбы 'элементы в футере'.

footer-bottom - это копирайт и линки (копирайт и линки могут спокойно показывать не в футере, а в хедере, например, и тогда это вообще не будет иметь смысла).
footer-middle - это вообще navigation-list - или что-то вроде. (их тоже можно было бы перести в aside или куда-то ещё, но это никак не значит, что это футер)
Ну и footer - это дествительно футер, который никак подругом собственно и не использовать.

Погляди, чтобы подобного рода ошибок по проекту не было, плез, чтобы всё именовалось именно по смыслу содержимого :)

**Comment by mglkn** [comment]
Спасибо за issue

https://github.com/mglkn/css-hotel-maket/commit/cbaa4a9a73c17cf419eb323863df4eaa5320f19f
https://github.com/mglkn/css-hotel-maket/commit/b4732c70f237f89d06e2e747734a850bdc9b8da4
https://github.com/mglkn/css-hotel-maket/commit/dcd9d62c9fd8ee5a4daba6ac646694e6ec53f1ce
https://github.com/mglkn/css-hotel-maket/commit/813c72d1386da20065d3f1bbed986e844c77d598
https://github.com/mglkn/css-hotel-maket/commit/69fb69646bfe61a3cc3b7ba03155b33d80896f32
https://github.com/mglkn/css-hotel-maket/commit/fa298923822af995955fd7f9290f5c9fce67a926

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95284841-7451ed00-0889-11eb-951f-a0e8afb66731.png)
Тут опечаточка небольшая.

Также сслыки на соц сети - нужно сделать именно ссылками на внешние источники. Можно просто сделать ссылки на главые страницы(инсты, фб, твиттера)

**Comment by mglkn** [comment]
Поправил!

https://github.com/mglkn/css-hotel-maket/commit/fb505fa929a08c8a9d85a5262c043dce162e4e84
https://github.com/mglkn/css-hotel-maket/commit/e5fd38018dd40b13d664d5218b68e216667cb825
