### ISSUE TITLE
Event handlers naming

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#13]
Имена обработчикам событий нужно давать в формате "handleElementNameEventName": [именование](https://github.com/fullstack-development/front-end-best-practices/blob/0eedda20077c13a9244b4364166f776ef046e871/JS/README.md#3.3).

**Comment by mglkn** [comment]
Done

https://github.com/mglkn/css-hotel-maket/commit/be34ac395ee42fdb939a3ee9bc6e4886ac184e9a
