### ISSUE TITLE
Scss / styles

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#14]
![image](https://user-images.githubusercontent.com/44312820/95712956-ebbfbc00-0c8f-11eb-8580-bb2aa1943d28.png)

Корень scss файла всегда должен быть один - блок БЭМ.
Для случаев, когда нужно использовать блок внутри, допустим, модификатора, можно использовать переменную - как на скрине, чтобы не копипастить блок. Название r - это код конвенш и сокращение от root, можно называть и r и root, но лучше на данном этапе именовать как root, имхо.
![image](https://user-images.githubusercontent.com/44312820/95712914-d480ce80-0c8f-11eb-97e7-220d9c6662ea.png)

![image](https://user-images.githubusercontent.com/44312820/95713081-1e69b480-0c90-11eb-894b-5325b50e7611.png)
Зачем использовать для кучи одинаковых элементов с одинаковой сущностью разные классы?
Можно же просто назвать элемент input и он будет использоваться для всех инпутов и сделать модификатор, для инпута с большим маргином.
Я это видел как минимум в нескольких местах, надо поправить.

**Comment by mglkn** [comment]
`Корень scss файла всегда должен быть один - блок БЭМ.`

Это "прошерстил". https://github.com/mglkn/css-hotel-maket/commit/28642f0c5f6595dc6794d8e4ecc471892821aa1b

**Comment by mglkn** [comment]
`Зачем использовать для кучи одинаковых элементов с одинаковой сущностью разные классы?
Можно же просто назвать элемент input и он будет использоваться для всех инпутов и сделать модификатор, для инпута с большим маргином.`

Где нашел - поправил.
