### ISSUE TITLE
Quotes in JS syntax

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#15]
В любом JS-like коде нужно использовать одинарные кавычки, к js-коду в pug это тоже относится.
![image](https://user-images.githubusercontent.com/44312820/95713387-a5b72800-0c90-11eb-8033-04d0275f5b95.png)

**Comment by mglkn** [comment]
Поправил.

https://github.com/mglkn/css-hotel-maket/commit/74a6add0e1ea52a61d6671b9ab2c67449a5914ea
