### ISSUE TITLE
Checks with multiple conditions

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#16]
Все проверки содержащие более одного условия должны быть вынесены. Выносить в отдельную архитектурную единицу - переменную или функцию. [тык](https://github.com/fullstack-development/front-end-best-practices/blob/0eedda20077c13a9244b4364166f776ef046e871/JS/README.md#1.9)

![image](https://user-images.githubusercontent.com/44312820/95713997-b61bd280-0c91-11eb-951c-da32dcba163e.png)

**Comment by mglkn** [comment]
Прошерстил код, вроде везде поправил.
