### ISSUE TITLE
UI-kit dev

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#17]
Не собирается сборка кита, из-за ошибки в регистре импорта:
![image](https://user-images.githubusercontent.com/44312820/96689747-03442680-13ad-11eb-95c7-9b19b2e76e52.png)
![image](https://user-images.githubusercontent.com/44312820/96689688-f1fb1a00-13ac-11eb-960c-f0ba4bb51d23.png)

**Comment by mglkn** [comment]
Я не смог воспроизвести эту проблему. (Проверял на WLS Ubuntu). Но понимаю, что проблема может возникнуть - я начал разрабатывать под виндой, и уже столкнулся с ней (У винды имена не case sensitive).

Я переименовал range-slider через `git mv` 
https://github.com/mglkn/css-hotel-maket/commit/52de6853eea75454c9cb625f3986e0e760913556

Сейчас должно собираться.
