### ISSUE TITLE
Plug-in libraries

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#18]
Все подключаемые библиотеки должны быть максимально абстрагированы от реализации проекта. Т.е. они должны использоваться 'под капотом', но при этом не сильно влиять на код.
Т.е. если либы требуют подключения своих скриптов/стилей непосредственно - то для этого должна быть отдельная папка(для всех используемых либ), где будут лежат стили и скрипты этих либ.
А твои компоненты должны быть реализованы твоей архитектурой, но просто с использованием файлов либы.

В общем, range slider должен быть по минимум связан с либой nouislider - все стили и скрипты из блока range-slider нужно будет вынести :)

**Comment by mglkn** [comment]
Отпилил slider и MaskInput.

https://github.com/mglkn/css-hotel-maket/commit/fdc17bf4c91628be257041071d9ef3d10708360c
https://github.com/mglkn/css-hotel-maket/commit/5a4b378a1cc3a04400e1c697051edfe144f0e76b
