### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#19]
Сейчас практически все классы сделаны с помощью статик методов. Обычно статические методы используются для реализации функций, принадлежащих классу, но не к каким-то конкретным его объектам. А у тебя ими полностью реализованы классы. This в них ссылается на конструктор класса, т.к. к инстансу они никакого отношения не имеют.

Суть использования классов заключается именно в том, что ты спокойно можешь создавать инстансы и они не будут конфликтовать, т.е. класс можно легко переиспользовать даже ничего не добавляя руками.
У тебя сейчас если я просто добавлю на страничку вторую форму/слайдер или что-то ещё скрипт будет работать только для одого из элементов.
Ты же не будешь инициализировать 1000 скриптов руками, если у тебя на страничке будет 1000 карточек у которых одинаковая логика.

**Comment by mglkn** [comment]
Отрефакторил.
