### ISSUE TITLE
Медиа запросы

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/css-hotel-maket#2]
Медиа запросы необходимо указывать не в конце файла стилей, а после каждого из классов. Для того чтобы можно было легко отследить как конкретный медиа запарос влияет на конкретный класс.
Скрин для примера:
![image](https://user-images.githubusercontent.com/10168007/89880629-a8dd5b80-dbee-11ea-8567-020dd3102d80.png)

**Comment by mglkn** [comment]
Это из требований к коду и я их пропустил. Сыплю голову пеплом.

**Comment by mglkn** [comment]
https://github.com/mglkn/css-hotel-maket/commit/4b3e9fd05c972eb3825e56684e2b597d91932c88#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by a-poluhin** [comment]
> Это из требований к коду и я их пропустил. Сыплю голову пеплом.
