### ISSUE TITLE
Donut

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/css-hotel-maket#4]
Отсутствует круг голосов
![image](https://user-images.githubusercontent.com/10168007/90736526-0b71de00-e2f8-11ea-89f4-c28c684f9134.png)
В макете это выглядит вот так
![image](https://user-images.githubusercontent.com/10168007/90736789-20e70800-e2f8-11ea-85f3-bc7191c7192b.png)

**Comment by mglkn** [comment]
https://github.com/mglkn/css-hotel-maket/commit/a5768492a4f67a3165df349c6024014f5ac09c15
