### ISSUE TITLE
Ошибка билда

### ISSUE THREAD

**Issue by a-poluhin** [mglkn/css-hotel-maket#5]
Не собираются страницы.
![image](https://user-images.githubusercontent.com/10168007/91287953-981a1180-e7ba-11ea-9b51-1978e2397d9a.png)

**Comment by mglkn** [comment]
Спасибо за issue!

Тут со мной сыграл плохую шутку виндовый git. Почему-то он не захотел пушить шрифты переименованые lower-case.
Я все исправил и проверил в wsl - все собирается. Так же написал более подробную инструкцию по сборке в README.

Команда собирающая проект `npm run build`. Собирает все страницы.
