### ISSUE TITLE
Project structure 

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#7]
БЭМ-блоки следует выделять в отдельные компоненты. Один блок - это один компонент, у которого своя папка с собственными pug, scss и js файлами(если необходимо). Причем эти файлы именуются в соответсвии с названием блока по нашми бестпрактисес(и название миксина тоже должно полностью совпадать с названием блока).

![image](https://user-images.githubusercontent.com/44312820/94648048-e5d6ec00-031b-11eb-8842-fbe3448bc124.png)
(скрин просто для примера)

Это нужно для быстрого поиска по проекту и нахождения нужных стилей/скриптов/разметки без танцев с бубном.

**Comment by mglkn** [comment]
Спасибо за issue

https://github.com/mglkn/css-hotel-maket/commit/7cb70b460a50608cb41871455d2bb2e570b63eed

**Comment by Feinminen** [comment]
Название файла миксина и блока должно полностью совпадать, миксины лучше именовать не в ловеркейсхафенейт, а в кебабкейсе.
![image](https://user-images.githubusercontent.com/44312820/95281738-11a92300-0882-11eb-8de7-557049105137.png)
Также и с названиями пэйджей:
![image](https://user-images.githubusercontent.com/44312820/95281985-9f850e00-0882-11eb-9e86-2256661ba1eb.png)
если блок пэйджи называется 'smth-page', то и  все файлы должны назваться 'smth-page'.

**Comment by mglkn** [comment]
Поправил.
