### ISSUE TITLE
Automatic import

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#8]
Для того чтобы не импортить необходимые стили в index.js каждого блока - можно настроить автоматический импорт. Меньше бойлерплейта, меньше проблем с неподключенными стилями.

![image](https://user-images.githubusercontent.com/44312820/94648518-e8861100-031c-11eb-840c-7ef070f28aeb.png)
Можно реализовать примерно вот так, только тут импортится по мимо стилей скрипты и тесты.

**Comment by mglkn** [comment]
Для этого проекта я использовал parcel, у него не такой продвинутый "require".
И я не вполне понимаю, как это должно работать. Я не должен импортить стили в index.js на уровне компонента? Делать это скриптом на уровне страницы?
