### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by Feinminen** [mglkn/css-hotel-maket#9]
![image](https://user-images.githubusercontent.com/44312820/94648618-1e2afa00-031d-11eb-9d2d-99b210bd862e.png)
По БЭМ для одного блока должна быть своя отдельная папка и свой отдельный pug, scss, js файл => нельзя так смешивать разные блоки и их стили.

И вообще тут же кнопки именно через модификаторы должны быть сделаны, у тебя хоть миксины и называются как модификаторы, но сама структура - это 4 разных блока, button-bordered/solid/solid-with-icon/simple.

![image](https://user-images.githubusercontent.com/44312820/94649003-f5efcb00-031d-11eb-876c-0e1bd4559bfa.png)
Тут же можно внутри стилей блока сделать:
```
 &_top-rounded {}
```
В scss всегда должен быть один корневой блок, внутри которого все стили элементов и модификаторов лежат (через & соответственно)

**Comment by mglkn** [comment]
Я переписал button. Теперь это один миксин "делающий" разные кнопки через модификаторы.

https://github.com/mglkn/css-hotel-maket/commit/9f3bea0b8dcb99edfa8a5906c6e5bf98fedbc85e
https://github.com/mglkn/css-hotel-maket/commit/963bfed2668a622e931dc31d3fbf9d0b2b2a668d

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95282098-eb37b780-0882-11eb-8a8d-4a7da4cc8011.png)
Тут у тебя так же не совпадает название файла и блока.
Причём тут у тебя иерархия начинается сразу с элемента БЭМ, а не с блока, чего в принципе быть не может :)
У тебя всегда должна быть вложенность:
```
.block
  .block__elemet
```
и никогда не может быть элементов без блока.

**Comment by Feinminen** [comment]
Также по БЭМ запрещены любые селекторы по тэгам.
![image](https://user-images.githubusercontent.com/44312820/95282322-600af180-0883-11eb-81a1-79a066c1dc8b.png)

По БЭМ у всех хтмл элементов должен быть свой класс, допускается не давать классы только инлайновым оберткам, у которых стилей быть не должно.
![image](https://user-images.githubusercontent.com/44312820/95282454-b2e4a900-0883-11eb-9571-428c395d1bdb.png)
Т.е. у 'a' - обязательно должен быть свой класс и тогда не придется накидвать стили по тэгу.

Также получается, что все стили, которые объявлены в root.scss - в корне не верны по БЭМ. Я понимаю что это странновато, но вот такая суть методологии :) 
Можешь оставить бокс сайзинг с универсальными селекторами и стили по шрифту на бади. А бэкграунд и колор лучше убрать, ибо из-за этого может быть много проблем, например если бы были разные цветовые решения на проекте.
![image](https://user-images.githubusercontent.com/44312820/95282414-95174400-0883-11eb-894e-f790ae2f809c.png)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95282748-4918cf00-0884-11eb-8f9f-7a1e06f062bf.png)
Также, если у тебя есть какой-то 'компонент', который просто собирает несколько миксинов вместе, то у него тоже должна быть обертка в виде блока.
Т.е. тут надо всё обернуть в блок ui-kit.

**Comment by Feinminen** [comment]
У тебя сейчас достаточно много элементов в проекте с практически идентичными стилями. Тут же явно напрашивается использование модификатора, чтобы был один класс и на модификатор просто переворачивлась стрелка.
![image](https://user-images.githubusercontent.com/44312820/95283725-aa41a200-0886-11eb-86d7-fa24bccad425.png)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95284572-ad3d9200-0888-11eb-9343-4c18ddf93506.png)
Тут стили явно не по БЭМ, в основном такое только в ui-kit-e встречал :)

**Comment by mglkn** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/44312820/95284572-ad3d9200-0888-11eb-9343-4c18ddf93506.png)
> Тут стили явно не по БЭМ, в основном такое только в ui-kit-e встречал :)

part-1 тут конечно мимо, но col-1-3 col-2-3 мне, все же, виделось семантичным.

Я все поправил.

**Comment by mglkn** [comment]
> 
> 
> Также по БЭМ запрещены любые селекторы по тэгам.
> ![image](https://user-images.githubusercontent.com/44312820/95282322-600af180-0883-11eb-81a1-79a066c1dc8b.png)
> 
> По БЭМ у всех хтмл элементов должен быть свой класс, допускается не давать классы только инлайновым оберткам, у которых стилей быть не должно.
> ![image](https://user-images.githubusercontent.com/44312820/95282454-b2e4a900-0883-11eb-9571-428c395d1bdb.png)
> Т.е. у 'a' - обязательно должен быть свой класс и тогда не придется накидвать стили по тэгу.
> 
> Также получается, что все стили, которые объявлены в root.scss - в корне не верны по БЭМ. Я понимаю что это странновато, но вот такая суть методологии :)
> Можешь оставить бокс сайзинг с универсальными селекторами и стили по шрифту на бади. А бэкграунд и колор лучше убрать, ибо из-за этого может быть много проблем, например если бы были разные цветовые решения на проекте.
> ![image](https://user-images.githubusercontent.com/44312820/95282414-95174400-0883-11eb-894e-f790ae2f809c.png)

На счет background и color в body
https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.7

**Comment by Feinminen** [comment]
> На счет background и color в body
> https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.7

Да, чёт я мальца поплыл, цвет бэкграунда и текста тоже можно оставить :)

**Comment by Feinminen** [comment]
В root же сейчас ещё остались стили по тэгам:
![image](https://user-images.githubusercontent.com/44312820/95711741-9d112280-0c8d-11eb-93ab-9ffbb9002006.png)

Также класc invisible, который используется в dropdown и должен лежать в dropdown (вероятнее всего, как модификатор)

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/95712301-be264300-0c8e-11eb-893a-35fc7c69da51.png)
В одном блоке нельзя менять стили других блоков.
Позиционирование таких элементов по бэст практисес делается через элементы-обертки родителей.

(название элемента, ествественно, будет другое, скрин просто для примера)
![image](https://user-images.githubusercontent.com/44312820/95712551-1bba8f80-0c8f-11eb-8fc5-3464e0d41ed4.png)

**Comment by mglkn** [comment]
> 
> 
> В root же сейчас ещё остались стили по тэгам:
> ![image](https://user-images.githubusercontent.com/44312820/95711741-9d112280-0c8d-11eb-93ab-9ffbb9002006.png)
> 
> Также класc invisible, который используется в dropdown и должен лежать в dropdown (вероятнее всего, как модификатор)

Тут я немного поплыл =) Почему-то подумал что из можно оставить. 

Поправил.

**Comment by mglkn** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/44312820/95712301-be264300-0c8e-11eb-893a-35fc7c69da51.png)
> В одном блоке нельзя менять стили других блоков.
> Позиционирование таких элементов по бэст практисес делается через элементы-обертки родителей.
> 
> (название элемента, ествественно, будет другое, скрин просто для примера)
> ![image](https://user-images.githubusercontent.com/44312820/95712551-1bba8f80-0c8f-11eb-8fc5-3464e0d41ed4.png)

Исправлено.

**Comment by Feinminen** [comment]
Ещё остались селекторы по тэгам.
![image](https://user-images.githubusercontent.com/44312820/96688196-12c27000-13ab-11eb-908b-9470de4adb34.png)
![image](https://user-images.githubusercontent.com/44312820/96688237-21108c00-13ab-11eb-8420-e45510e5684e.png)

Все модификаторы/ стили для псеводоклассов/селекторов должны быть описаны внутри элемента, чтобы было сразу видно к чему они относятся.
![image](https://user-images.githubusercontent.com/44312820/96688580-895f6d80-13ab-11eb-9748-bf5f4dac2225.png)

```
.calendar {
  &__day {
    &:focus {}
    &_one-selected {}
    ...
  }
}
```

**Comment by Feinminen** [comment]
![image](https://user-images.githubusercontent.com/44312820/96689886-31c20180-13ad-11eb-92ab-06212937b793.png)
Название миксина и блока отличается

**Comment by mglkn** [comment]
Порефакторил.

Вроде все "выгреб".
